#服务器端口
server:
  port: 9999

#配置spring
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket?characterEncoding=UTF-8
    username: root
    password: 123456

#配置日志打印
logging: 
  level: 
    com: 
      woniu: DEBUG

#配置mybatis
mybatis:
  type-aliases-package: com.woniu.domain
  mapper-locations: classpath:com/woniu/dao/*.xml

